### PR TITLE
Added Mingkay card

### PR DESCRIPTION
**Pull request by RioCantre**
Hi, I added a new card titled "Mingkay".

### CODE REVIEW

**Comment by RioCantre** [comment]
HacktoberFest Maintainers

**Review by J3ffJessie — APPROVED** [review]
Lovely. Thank you for contributing.

**Comment by RioCantre** [comment]
Thank you! I'm wondering if there is a label called "Hacktoberfest accepted"  to my PR?

**Comment by RioCantre** [comment]
Got it! A waiting game.

**Comment by mateahoward** [comment]
Hey @RioCantre 👋!

As we're nearing the end of HacktoberFest, our team wanted to thank you once again for your contribution! We hope you've enjoyed participating in our little challenge this year and have maybe even had a chance to learn something new as well 🙌

If you'd like to stick around and (in the near future) start practicing on similar projects with junior developers from our group please feel free to join our discord channel - we'd love to have you 😀

[https://discord.gg/58YEbSgSAc](https://discord.gg/58YEbSgSAc)

Once again, thank you and we hope it was as fun for you as it was for us 🤗
[Junior Developer Group](https://junior-developer-group.com/)

**Pull request merged**
