### PR TITLE
added my pet sheru

### PR DESCRIPTION
**Pull request by ajjju1**
Hey,
This is ajmal malik, I added my pet cat sheru.

### CODE REVIEW

**Review by J3ffJessie — APPROVED** [review]

**Comment by J3ffJessie** [comment]
Hello @ajjju1 if you could possibly merge recent changes from main into your branch we will be able to merge after the conflicts are resolved. Thank you.

**Comment by J3ffJessie** [comment]
@ajjju1 i closed your other PR off, you need to merge main into your forked branch. This will pull any changes that were merged after you forked the main branch to do your card.

**Comment by ajjju1** [comment]
> @ajjju1 i closed your other PR off, you need to merge main into your forked branch. This will pull any changes that were merged after you forked the main branch to do your card.

 @J3ffJessie i have already merge main into my forked branch.

**Comment by J3ffJessie** [comment]
@ajjju1 thank you. Merge conflicts are gone and I'm merging for you now. Thank you for contributing.

**Comment by mateahoward** [comment]
Hey  @ajjju1 👋!

As we're nearing the end of HacktoberFest, our team wanted to thank you once again for your contribution! We hope you've enjoyed participating in our little challenge this year and have maybe even had a chance to learn something new as well 🙌

If you'd like to stick around and (in the near future) start practicing on similar projects with junior developers from our group please feel free to join our discord channel - we'd love to have you 😀

[https://discord.gg/58YEbSgSAc](https://discord.gg/58YEbSgSAc)

Once again, thank you and we hope it was as fun for you as it was for us 🤗
[Junior Developer Group](https://junior-developer-group.com/)

**Pull request merged**
