### PR TITLE
Added card for hazel

### PR DESCRIPTION
**Pull request by SakshamPranay**
Please merge it.

### CODE REVIEW

**Comment by J3ffJessie** [comment]
You did not implement any CSS styling for your card, was that intentional or do you want to add in styling for your card before merging? @SakshamPranay

**Comment by SakshamPranay** [comment]
That was intentional sir. Will it be valid for hactoberfest?

**Comment by J3ffJessie** [comment]
> That was intentional sir. Will it be valid for hactoberfest?

Yeah, shouldn't be an issue just wanted to make sure before I reviewed and approved it.

**Review by J3ffJessie — APPROVED** [review]
Looks good to me.

**Comment by J3ffJessie** [comment]
@SakshamPranay can you merge main into your branch and push your branch again with the updated changes. After that I will merge you in.

**Comment by mateahoward** [comment]
Hiya both :D  I've gone ahead and merged main into your branch so that we're good to merge and don't have to repeat this once we have another contribution in :)

**Comment by mateahoward** [comment]
Hey @SakshamPranay 👋!

As we're nearing the end of HacktoberFest, our team wanted to thank you once again for your contribution! We hope you've enjoyed participating in our little challenge this year and have maybe even had a chance to learn something new as well 🙌

If you'd like to stick around and (in the near future) start practicing on similar projects with junior developers from our group please feel free to join our discord channel - we'd love to have you 😀

[https://discord.gg/58YEbSgSAc](https://discord.gg/58YEbSgSAc)

Once again, thank you and we hope it was as fun for you as it was for us 🤗
[Junior Developer Group](https://junior-developer-group.com/)

**Pull request merged**
