### PR TITLE
fluffy added

### PR DESCRIPTION
**Pull request by SahbanAlam**
Hello, this is my first time contributing to open source. If there's anything I didn't do according to the rules then do let me know.
Please accept it under Hacktoberfest tag.

### CODE REVIEW

**Comment by mateahoward** [comment]
Hey @SahbanAlam :D we seem to have a conflict here :D would you be okay to have a look at that before we merge it in? :D

**Comment by SahbanAlam** [comment]
I'm totally ok with it but what should I do now ?

**Comment by mateahoward** [comment]
Hey ☺️ it's a bit late for me at the moment but maybe @Junior-Developer-Group/hacktoberfest-maintainers from other timezones can help us out 😁

**Comment by J3ffJessie** [comment]
Please fix merge conflicts before merge can be completed. It appears you do not have the most up to date changes from the main repository. Do a git pull inside the repository to get the most up to date changes and then re commit your changes.

**Review by J3ffJessie — APPROVED** [review]
Thank you for fixing conflicts. Welcome Fluffy!!!

**Comment by mateahoward** [comment]
Hey @SahbanAlam 👋!

As we're nearing the end of HacktoberFest, our team wanted to thank you once again for your contribution! We hope you've enjoyed participating in our little challenge this year and have maybe even had a chance to learn something new as well 🙌

If you'd like to stick around and (in the near future) start practicing on similar projects with junior developers from our group please feel free to join our discord channel - we'd love to have you 😀

[https://discord.gg/58YEbSgSAc](https://discord.gg/58YEbSgSAc)

Once again, thank you and we hope it was as fun for you as it was for us 🤗
[Junior Developer Group](https://junior-developer-group.com/)

**Pull request merged**
