### PR TITLE
Added Red Panda card

### PR DESCRIPTION
**Pull request by jaebirds**

### CODE REVIEW

**Comment by jaebirds** [comment]
It seems like it wants to delete some other people's cards. I'm not sure how to fix this.

**Comment by jaebirds** [comment]
Awesome, thank you!

**Comment by mateahoward** [comment]
Had a look once more just in case, I think we're good to go so I'll merge it in :D :D

**Comment by mateahoward** [comment]
Hey @jaebirds 👋!

As we're nearing the end of HacktoberFest, our team wanted to thank you once again for your contribution! We hope you've enjoyed participating in our little challenge this year and have maybe even had a chance to learn something new as well 🙌

If you'd like to stick around and (in the near future) start practicing on similar projects with junior developers from our group please feel free to join our discord channel - we'd love to have you 😀

[https://discord.gg/58YEbSgSAc](https://discord.gg/58YEbSgSAc)

Once again, thank you and we hope it was as fun for you as it was for us 🤗
[Junior Developer Group](https://junior-developer-group.com/)

**Pull request merged**
