### PR TITLE
Milo

### PR DESCRIPTION
**Pull request by Lokesh-Rathore**

### CODE REVIEW

**Comment by Lokesh-Rathore** [comment]
Added my best friend Milo.

**Comment by Denice-S** [comment]
Hi Lokesh-Rathore, I've noticed you haven't added any CSS to go with the card of your dog Milo ( the only file changed is index.html), is this intentional ?  as looking at it the image and text are all right up against the left side of the card,  and I wanted to check before merging in.

**Comment by Lokesh-Rathore** [comment]
Actually I added some inline css.It's in the html file only.But if you want I can make changes as you say.

**Comment by Denice-S** [comment]
Hi Lokesh, yes I noticed you added some inline styles but what was confusing me is that is if you hover on your card it changes height and it also has a shadow which is not specified in your inline-styles for milo card. 

You card is inheriting CSS styling from someone else's card ( they have styles applied to a class of "card").

 To prevent this, instead of having you card class as : class="card" you could set it to something different and more specific for example class="milo-card" and it would not inherit those styles.

Do you want to make that change please? and then do another git push?

It is completely up to you whether to put your CSS into a separate file or do it inline - but it is considered best  practice to put CSS into  a CSS file as it keeps the HTML cleaner and easier to read especially if we have a lot of styling.

**Comment by Denice-S** [comment]
Hi  Lokesh, please could you change your line <div class="card" so that it is something like <div class="milo-card"
Don't worry you have not copied anyone else's code at all, we just have a clash with css names, thats all.  If you make the change and git push again I can merge it in.

**Comment by Lokesh-Rathore** [comment]
On it

**Comment by mateahoward** [comment]
Hey both :D We will indeed need to add a change so thank you very much @Denice-S for spotting that :D @Lokesh-Rathore I'm sorry but we don't have bootstrap on this repo, its a plain HTML/CSS repo so, in that case, _you are_ using someone else's CSS and I'm very happy to see you're already on it :D

**Pull request closed without merging**
