### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by SeptiyanNugroho**
Animated Website Home Page
Hacktoberpet2021

### CODE REVIEW

**Comment by J3ffJessie** [comment]
We are not looking for animations on this repository. However, if you want to add a card to the repository in favor of your favorite pet or favorite animal feel free please. Unfortunately I cannot approve your PR as it is not in standing with our Guidelines for this repository @SeptiyanNugroho

**Comment by SeptiyanNugroho** [comment]
please give me. What is you need about repository ??

Pada tanggal Min, 3 Okt 2021 pukul 11.47 J3ffJessie <
***@***.***> menulis:

**Comment by J3ffJessie** [comment]
> please give me. What is you need about repository ??


Take a look at the README as it gives specific instructions regarding this repository and what we are looking for in contributions.

**Comment by SeptiyanNugroho** [comment]
I cant uploud animal images ??
please hepl me ??


Pada tanggal Min, 3 Okt 2021 pukul 11.53 J3ffJessie <
***@***.***> menulis:

**Comment by J3ffJessie** [comment]
> I cant uploud animal images ??
> please hepl me ??
> 


I am sorry but there is nothing I can do for you. If you cannot follow the guidelines and rules for the repository I cannot allow your PR to be added.

**Pull request closed without merging**
