### PR TITLE
Shera added

### PR DESCRIPTION
**Pull request by Roshan5401**
shera added please accept it under hacktoberfest tag.

### CODE REVIEW

**Comment by J3ffJessie** [comment]
Please fix merge conflicts before merge can be completed. It appears you do not have the most up to date changes from the main repository. Do a git pull inside the repository to get the most up to date changes and then re commit your changes.

**Comment by J3ffJessie** [comment]
@Roshan5401 please merge main in again to your repo and you should be good. Too many PRs at one time causing the conflicts. Apologies. After main pull and recommit should be good to merge.

**Review by J3ffJessie — APPROVED** [review]
@Roshan5401 thank you for contributing and being patient with the changes. Very much appreciated.

**Comment by mateahoward** [comment]
Hey @Roshan5401 👋!

As we're nearing the end of HacktoberFest, our team wanted to thank you once again for your contribution! We hope you've enjoyed participating in our little challenge this year and have maybe even had a chance to learn something new as well 🙌

If you'd like to stick around and (in the near future) start practicing on similar projects with junior developers from our group please feel free to join our discord channel - we'd love to have you 😀

[https://discord.gg/58YEbSgSAc](https://discord.gg/58YEbSgSAc)

Once again, thank you and we hope it was as fun for you as it was for us 🤗
[Junior Developer Group](https://junior-developer-group.com/)

**Pull request merged**
