### PR TITLE
Add pet and contributor section

### PR DESCRIPTION
**Pull request by caseyocampo**
Added a contributor section to avoid breaking current content and styles. Additionally, I've added a separate stylesheet for my pet card. @HacktoberFestMaintainers

I'm am not sure how to tag 'HacktoberFest Maintainers' in a pull request.

### CODE REVIEW

**Review by J3ffJessie — CHANGES_REQUESTED** [review]
If you could, please move your macs.css styling into the main styles.css file so that all of our styles are located in the same file.  Also, remove the Added pets contributor section h2 as it only sits above your card when displayed, or you can give it a go at putting it in place and styling so that it displays above all Pets that are added and stays centered.  Once you make the changes I will review again and take a look. Thank you for contributing. Also, once you make changes tag me as a reviewer on the right side tab in Github when you submit your code as a reviewer.

**Comment by connorocampo** [comment]
@J3ffJessie I believe I've resolved the issue as requested. Thank you for letting me participate!

**Review by J3ffJessie — APPROVED** [review]
Awesome, thank you so much for contributing Macs to the list of awesome pets.  Thank you for making the changes as well.  Approved and merging shortly.

**Comment by mateahoward** [comment]
Hey @connorocampo 👋!

As we're nearing the end of HacktoberFest, our team wanted to thank you once again for your contribution! We hope you've enjoyed participating in our little challenge this year and have maybe even had a chance to learn something new as well 🙌

If you'd like to stick around and (in the near future) start practicing on similar projects with junior developers from our group please feel free to join our discord channel - we'd love to have you 😀

[https://discord.gg/58YEbSgSAc](https://discord.gg/58YEbSgSAc)

Once again, thank you and we hope it was as fun for you as it was for us 🤗
[Junior Developer Group](https://junior-developer-group.com/)

**Pull request merged**
