### PR TITLE
Added Pluto pet-card

### PR DESCRIPTION
**Pull request by JOS-RE**
I have added a pet card for my pet Pluto.
Please merge this Pull request. @J3ffJessie

### CODE REVIEW

**Comment by mateahoward** [comment]
Hey @JOS-RE :) Thank you very much for your contribution, I've tagged our HacktoberFest Maintainers who'll be having a look at your PR after work today and seeing if we can merge it in :)

**Comment by JOS-RE** [comment]
Thank you so much :D

**Comment by fitzcodes** [comment]
Hi there @JOS-RE ! There was another PR that was merged while this one was being looked at. Please merge main into your forked branch, which should resolve conflicts and then we'll get you merged in. Thanks!

**Comment by JOS-RE** [comment]
@fitzcodes , I have done as instructed and resolved the conflicts, Thanks

**Review by fitzcodes — APPROVED** [review]
Looks good. Only real issue is your settings aren't set to pick up and use the prettier config file. Which undid a lot of formatting which is why there are so many differences within the compared files. Something to look out for in future endeavours.

**Comment by JOS-RE** [comment]
Thank you for bringing this to my notice. I look forward to make ammends in the editor Configurations and Be extra careful :)

**Comment by mateahoward** [comment]
Hey @JOS-RE 👋!

As we're nearing the end of HacktoberFest, our team wanted to thank you once again for your contribution! We hope you've enjoyed participating in our little challenge this year and have maybe even had a chance to learn something new as well 🙌

If you'd like to stick around and (in the near future) start practicing on similar projects with junior developers from our group please feel free to join our discord channel - we'd love to have you 😀

[https://discord.gg/58YEbSgSAc](https://discord.gg/58YEbSgSAc)

Once again, thank you and we hope it was as fun for you as it was for us 🤗
[Junior Developer Group](https://junior-developer-group.com/)

**Pull request merged**
